sqlchat/sqlchat

- components/ChatView/index.tsx
- package.json
- pages/api/chat.ts
- pnpm-lock.yaml
- utils/openai.ts
> feat: implement token counter

- src/components/CreateConnectionModal.tsx
> feat: add SSL field to connection

- README.md
Minor changes to get more accurate grammar and spell-check in the README-file.
> chore: minor gramatic/spell-check changes

- src/components/ConversationView/index.tsx
- src/components/LocaleSelector.tsx
- src/components/OpenAIApiConfigView.tsx
- src/components/SettingModal.tsx
- src/pages/api/chat.ts
- src/store/setting.ts
- src/types/setting.ts
> feat: add openai api key and endpoint in setting

- src/components/ConnectionSidebar.tsx
- src/components/ConversationView/index.tsx
Wait for our announcement in the product hunt.
> chore: show product hunt banner

- src/locales/es.json
🎨 style(es.json): add new keys and values for connection and assistant
🚀 chore(es.json): add new banner messages
The connection object now has new keys and values for the database type, title, host, port, database name, username, and password. The assistant object now has a new key and value for creating a new bot. The banner object now has two new messages, one for warning non-select SQL statements and another for promoting the product launch on Product Hunt.
> Update on Spanish Translation

- package.json
- pnpm-lock.yaml
- src/components/kit/Select.tsx
max-h + overflow-auto
advantages:
- the dynamic height of select
problems:
- Scrollbars created with Tailwind CSS. Style cannot be changed. It is ugly and inconsistent in style. the scroll bar didn't have a round! May not be visible in GIF. the edge of the scrollbar is rectangular.
[ref](https://tailwindcss.com/docs/overflow#scrolling-horizontally-always)
solid height + scrollArea
advantages:
- no scrollbar. It has a style consistent.
problems:
- solid height, unless the numbers of the select option 
I decided to mix the two solutions, to judge whether the number exceeds the limit of height. If true solution 2 else solution1.
Because it is a limit from radix-ui
ref: https://github.com/radix-ui/primitives/issues/1495
> feat: make select component scrollable

- README.md
- README.zh-CN.md
docs(README.md): Optimize document layout, add references to keywords.
feat(README.zh-CN.md): New add a Chinese document.
> feat: add a Chinese document

- README.zh-CN.md
1. add space between Chinese and English Word
2. correct error translation
> chore: fix some error format in Chinese document

- README.zh-CN.md
chore(README.zh-CN.md): fix document target jump
> chore: fix document target jump

- src/components/PricingView.tsx
- src/components/SettingView.tsx
- src/pages/setting/index.tsx
> chore: add dark mode styles to setting page

- src/components/CreateConnectionModal.tsx
fix #86
another change is auto-fixed by eslint👀
> chore: check the title is not null when creating connection

- README.md
- README.zh-CN.md
Add TiDB Cloud to databases list in README markdown document.
> feat: readme add tidb into databases list

- README.md
- README.zh-CN.md
docs(README.md): improve introduction.
docs(README.zh-CN.md): sync doc.
> docs: sync doc

- src/components/ConversationView/Header.tsx
- src/components/ConversationView/index.tsx
- src/components/SchemaDrawer.tsx
https://github.com/sqlchat/sqlchat/assets/24653555/da80bf55-5890-4531-aad5-d63bc6562e1d
> chore: add schema drawer

- src/components/ConnectionSidebar.tsx
- src/components/ConversationTabsView.tsx
- src/components/ConversationView/Header.tsx
BTW, it's in the dev flag. Once the left sidebar content is enriched, we can move it to production.
https://github.com/sqlchat/sqlchat/assets/24653555/a78e7b28-7581-49a2-8b38-6e932038cafa
> feat: implement conversation tabs in header

- src/store/connection.ts
> chore: replace supabase with neon as the sample database

- src/components/ConnectionSidebar.tsx
delete incorrect side Effect dependent🤔 otherwise it will rerender stopless and cause can't open the setting page when no database is selected
> fix: can't open setting when no database be selected

- src/components/ConnectionSidebar.tsx
> fix: no select first schema when create a new conversation

- src/components/ConversationView/index.tsx
🤯 I forget to delete it and it is unnecessary.
> chore: delete unnecessary console.log

- pnpm-lock.yaml
- src/components/ConnectionSidebar.tsx
- src/components/ConversationView/index.tsx
because when connecting a new database. the head of `schemaList` may be undefined when loading. it may cause unwanted rerender
> fix: unwanted rerender when connect a new database

- README.es-ES.md
- README.md
- README.zh-CN.md
- src/locales/es.json
Update on some of the Spanish Traslations lines, and added a README.md in spanish, modified the existing README.md to add the link for the spanish README.
> Updates on es_ES translations

- process.d.ts
- src/pages/api/auth/[...nextauth].ts
#147
supported to be configurable the outgoing mail
> configurable outgoing mailbox

- README.md
Adding button to the top of the readme in shields.io format
> Adding one-click deploy button for RepoCloud.io to top to match Vercel button
